version: '3.8'
services:
  homeiapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5185:5185"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5185
    volumes:
      - ./HomeIEApi/Database:/Database

